set_property PACKAGE_PIN W5  [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]
set_property PACKAGE_PIN U18  [get_ports rst_btn]
set_property IOSTANDARD LVCMOS33 [get_ports rst_btn]
set_property PACKAGE_PIN T18  [get_ports save_btn]
set_property IOSTANDARD LVCMOS33 [get_ports save_btn]
set_property PACKAGE_PIN W19  [get_ports check_btn]
set_property IOSTANDARD LVCMOS33 [get_ports check_btn]
set_property PACKAGE_PIN V17  [get_ports mode_sw]
set_property IOSTANDARD LVCMOS33 [get_ports mode_sw]
set_property PACKAGE_PIN U16  [get_ports unlock_led]
set_property IOSTANDARD LVCMOS33 [get_ports unlock_led]
set_property PACKAGE_PIN E19  [get_ports error_led]
set_property IOSTANDARD LVCMOS33 [get_ports error_led]
set_property PACKAGE_PIN U19  [get_ports save_led]
set_property IOSTANDARD LVCMOS33 [get_ports save_led]
set_property PACKAGE_PIN V19  [get_ports press_led]
set_property IOSTANDARD LVCMOS33 [get_ports press_led]
set_property PACKAGE_PIN P1   [get_ports mode_led14]
set_property IOSTANDARD LVCMOS33 [get_ports mode_led14]
set_property PACKAGE_PIN L1   [get_ports mode_led15]
set_property IOSTANDARD LVCMOS33 [get_ports mode_led15]
set_property PACKAGE_PIN U2   [get_ports {an[0]}]
set_property PACKAGE_PIN U4   [get_ports {an[1]}]
set_property PACKAGE_PIN V4   [get_ports {an[2]}]
set_property PACKAGE_PIN W4   [get_ports {an[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[*]}]
set_property PACKAGE_PIN W7   [get_ports {seg[0]}]
set_property PACKAGE_PIN W6   [get_ports {seg[1]}]
set_property PACKAGE_PIN U8   [get_ports {seg[2]}]
set_property PACKAGE_PIN V8   [get_ports {seg[3]}]
set_property PACKAGE_PIN U5   [get_ports {seg[4]}]
set_property PACKAGE_PIN V5   [get_ports {seg[5]}]
set_property PACKAGE_PIN U7   [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[*]}]
set_property PACKAGE_PIN V7   [get_ports dp]
set_property IOSTANDARD LVCMOS33 [get_ports dp]
set_property PACKAGE_PIN J1   [get_ports {row[0]}]
set_property PACKAGE_PIN L2   [get_ports {row[1]}]
set_property PACKAGE_PIN J2   [get_ports {row[2]}]
set_property PACKAGE_PIN G2   [get_ports {row[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[*]}]
set_property PACKAGE_PIN H1   [get_ports {col[0]}]
set_property PACKAGE_PIN K2   [get_ports {col[1]}]
set_property PACKAGE_PIN H2   [get_ports {col[2]}]
set_property PACKAGE_PIN G3   [get_ports {col[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[*]}]
set_property PULLUP TRUE [get_ports {col[0]}]
set_property PULLUP TRUE [get_ports {col[1]}]
set_property PULLUP TRUE [get_ports {col[2]}]
set_property PULLUP TRUE [get_ports {col[3]}]
set_property PACKAGE_PIN A14  [get_ports lcd_rs]
set_property PACKAGE_PIN A16  [get_ports lcd_en]
set_property PACKAGE_PIN B15  [get_ports {lcd_d[0]}]
set_property PACKAGE_PIN A15  [get_ports {lcd_d[1]}]
set_property PACKAGE_PIN B16  [get_ports {lcd_d[2]}]
set_property PACKAGE_PIN B17  [get_ports {lcd_d[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_rs]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_en]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_d[*]}]
set_property PACKAGE_PIN K17  [get_ports buzzer]
set_property IOSTANDARD LVCMOS33 [get_ports buzzer]
set_property PACKAGE_PIN M18  [get_ports led_green]
set_property IOSTANDARD LVCMOS33 [get_ports led_green]
set_property PACKAGE_PIN N17  [get_ports led_red]
set_property IOSTANDARD LVCMOS33 [get_ports led_red]
set_property PACKAGE_PIN P18  [get_ports led_yellow]
set_property IOSTANDARD LVCMOS33 [get_ports led_yellow]
set_property PACKAGE_PIN L17  [get_ports ext_save_btn]
set_property IOSTANDARD LVCMOS33 [get_ports ext_save_btn]
set_property PULLUP TRUE [get_ports ext_save_btn]
set_property PACKAGE_PIN M19  [get_ports ext_check_btn]
set_property IOSTANDARD LVCMOS33 [get_ports ext_check_btn]
set_property PULLUP TRUE [get_ports ext_check_btn]
set_property PACKAGE_PIN P17  [get_ports ext_rst_btn]
set_property IOSTANDARD LVCMOS33 [get_ports ext_rst_btn]
set_property PULLUP TRUE [get_ports ext_rst_btn]
set_property PACKAGE_PIN R18  [get_ports ext_mode_btn]
set_property IOSTANDARD LVCMOS33 [get_ports ext_mode_btn]
set_property PULLUP TRUE [get_ports ext_mode_btn]
set_false_path -from [get_ports rst_btn]
set_false_path -from [get_ports save_btn]
set_false_path -from [get_ports check_btn]
set_false_path -from [get_ports mode_sw]
set_false_path -from [get_ports {col[*]}]
set_false_path -from [get_ports ext_save_btn]
set_false_path -from [get_ports ext_check_btn]
set_false_path -from [get_ports ext_rst_btn]
set_false_path -from [get_ports ext_mode_btn]
